### ISSUE TITLE
win10下pydbgeng报错

### ISSUE THREAD

**Issue by whiteHat001** [walkerfuz/PyDbgEng#2]
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\hackyzh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\hackyzh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hackyzh\Desktop\morph\node\morph.py", line 53, in pre_fuzz
    dbg.run(sample_proc)
  File "C:\Users\hackyzh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pydbgeng-0.0.5-py3.6.egg\PyDbgEng\windows\UserDebugger.py", line 36, in run
    dbg_eng_dll_path = self.p)# symbols_path = SymbolsPath
  File "C:\Users\hackyzh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pydbgeng-0.0.5-py3.6.egg\PyDbgEng\windows\core\ProcessCreator.py", line 19, in __init__
    CommandLine = command_line, CreateFlags = creation_flags)
_ctypes.COMError: (-2147024846, '不支持该请求。', (None, None, None, 0, None))

**Comment by walkerfuz** [comment]
该错误的原因是：你在win10x64环境下安装了32位的Python环境。
解决方法：将Python更换为64位版本，重新安装comtypes和PyDbgEng即可。
